name: CI

on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Norminette.
              run: |
                  python3 -m pip install --upgrade pip setuptools
                  python3 -m pip install norminette

            - name: Run Norminette.
              run: norminette

